version: "3"

services:
  coverage_api:
    build:
      context: ./coverage-api/
    volumes:
      - ./coverage-api:/src
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
      - mongo_db

  clearinghouse_api:
    build:
      context: ./mock-clearinghouse-api
    volumes:
      - ./mock-clearinghouse-api:/src
    ports:
      - "8001:8001"

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: nirvana
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./overrides-seed-data/data:/var/lib/mysql
      - ./overrides-seed-data/init:/docker-entrypoint-initdb.d
      - ./overrides-seed-data/sql_config:/etc/mysql/conf.d

  mysql_db_analytics:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: analytics
      MYSQL_ROOT_PASSWORD: root_password_analytics
      MYSQL_USER: admin_analytics
      MYSQL_PASSWORD: password_analytics
    ports:
      - "3307:3306"
    volumes:
      - ./analytics-data/data:/var/lib/mysql
      - ./analytics-data/init:/docker-entrypoint-initdb.d
      - ./analytics-data/sql_config:/etc/mysql/conf.d
 
  mongo_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: nirvana
    ports:
      - "27017:27017"

  dagster-webserver:
    build: ./pipelines
    ports:
      - "3000:3000"
    volumes:
      - "./pipelines/coverage_pipeline.py:/opt/dagster/app/coverage_pipeline.py"
      - "./pipelines/workspace.yaml:/opt/dagster/app/workspace.yaml"
      - "./pipelines/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml"

    environment:
      DAGSTER_HOME: "/opt/dagster/dagster_home/"

  dagster-daemon:
      build: ./pipelines
      volumes:
        - "./pipelines/coverage_pipeline.py:/opt/dagster/app/coverage_pipeline.py"
        - "./pipelines/workspace.yaml:/opt/dagster/app/workspace.yaml"
        - "./pipelines/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml"
      environment:
        DAGSTER_HOME: "/opt/dagster/dagster_home/"
      entrypoint: ["dagster-daemon", "run"]

  metabase:
    image: scurrilous/metabase:latest
    ports:
      - "3002:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_EMOJI_IN_LOGS: "false"